# Generated by Django 4.1.7 on 2023-06-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0002_studentprofile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
