# Generated by Django 4.1.7 on 2023-06-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0003_studentprofile_email_studentprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='first_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='last_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
