# Generated by Django 4.1.7 on 2023-06-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0008_resource_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_URL',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='PMS/file/resources/'),
        ),
    ]
