# Generated by Django 4.1.7 on 2023-06-15 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0009_alter_resource_file_url_alter_resource_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TASK_OVERDUE', 'Task Overdue'), ('NEW_TASK', 'Added New Task'), ('CHAT_TASK', 'Chat In Task'), ('NEW_RESOURCE', 'Added New Resource'), ('CHAT_RESOURCE', 'Chat In Resource'), ('NEW_MEETING_RECORD', 'Added New Meeting Record'), ('UPDATED_MEETING_RECORD', 'Updated Meeting Record Status')], max_length=24)),
                ('chat_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_resource', to='PMS.resource')),
                ('chat_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_task', to='PMS.task')),
                ('new_meeting_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_mr', to='PMS.meetingrecord')),
                ('new_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_resource', to='PMS.resource')),
                ('new_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_task', to='PMS.task')),
                ('overdue_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overdue_task', to='PMS.task')),
                ('updated_meeting_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_mr', to='PMS.meetingrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
