# Generated by Django 4.1.7 on 2023-06-15 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='chat_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_resource', to='PMS.resource'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='chat_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_task', to='PMS.task'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='new_meeting_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_mr', to='PMS.meetingrecord'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='new_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_resource', to='PMS.resource'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='new_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_task', to='PMS.task'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='overdue_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overdue_task', to='PMS.task'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_meeting_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_mr', to='PMS.meetingrecord'),
        ),
    ]
