# Generated by Django 4.1.7 on 2023-06-16 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0013_alter_notification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 5, 21)),
            preserve_default=False,
        ),
    ]
